### ISSUE TITLE
one sug

### ISSUE THREAD

**Issue by javakam** [anzewei/ParallaxBackLayout#1]
I think it is a wrong way to use it like this :
**"Other Usage
Your Activitys can extends Activity or FragmentActivity es.
 public abstract class BaseActivity extends Activity {......" in your README.md**
it may be : 
First : public abstract class ParallaxActivityBase extends FragmentActivity  (if your app based on FragmentActivity) ;
Second : public abstract class BaseFragmentActivity extends ParallaxActivityBase  (BaseFragmentActivity  is root Activity of your app) .

**End,thank you very much,your blog is useful to me !**

**Comment by anzewei** [comment]
可能我描述的有问题吧，我想表达的是可以自己通过helper在任意Activity上实现滑动返回效果

**Comment by javakam** [comment]
A ( FragmentActivity ),B  ( Fragment),C  ( FragmentActivity )，先从A到B，但是从B到A侧滑回去的时候，A页面是灰色的如果采用你说的方式. 在使用SwipeBackLayout时候也会有这个问题.

**Comment by anzewei** [comment]
是不是你的Activity没有设置透明

**Comment by anzewei** [comment]
是否可以录制个gif看下

**Comment by javakam** [comment]
可以qq123222557
