### ISSUE TITLE
快速滑动有问题

### ISSUE THREAD

**Issue by csh159** [anzewei/ParallaxBackLayout#10]

**Comment by anzewei** [comment]
能具体说明下吗

**Comment by csh159** [comment]
快速滑动的的时候，滑不过去

**Comment by anzewei** [comment]
好的，上一个版本默认没有增加fling，临时解决方案是：可以通过设置setScrollThresHold 调整松开时的滑动比例，超过这个比例后会返回之前页面；
对于fling的方案近期会更新，包括一些配置选项
