### ISSUE TITLE
混淆代码后会有问题，枚举类型需要保护

### ISSUE THREAD

**Issue by maoruibin** [anzewei/ParallaxBackLayout#11]
如题

**Comment by YorekLiu** [comment]
我也遇到了同样的问题，然后使用了如下的混淆配置：

>-keep class com.github.anzewei.parallaxbacklayout.** { *; }
>-keepclassmembers class com.github.anzewei.parallaxbacklayout.** { *; }
>-dontwarn com.github.anzewei.parallaxbacklayout.**

**Comment by maoruibin** [comment]
嗯嗯，我已经提交了 PR #13 。不过作者好像挺忙的样子，一直没怎么处理
