### ISSUE TITLE
部分机器关闭后页面闪

### ISSUE THREAD

**Issue by xiedeliang** [anzewei/ParallaxBackLayout#14]
当我打开页面后，通过右划关闭当前页面，回到上一个页面后，挣个UI发生了闪一下的情况，机器是华为 Nova 3

**Comment by anzewei** [comment]
用的代码还是gradle

**Comment by xiedeliang** [comment]
问题已经修复啦，谢谢


发自我的 iPhone

**Comment by xiedeliang** [comment]
已经修复，activity关闭动画导致的

发自我的 iPhone

**Comment by csh159** [comment]
@xiedeliang 怎么修复的？
