### ISSUE TITLE
作者求助一下

### ISSUE THREAD

**Issue by punszeto** [anzewei/ParallaxBackLayout#2]
为毛我写一个基类，跟你ParallaxActivityBase 就是一模一样，然后build之后，滑的效果是一片空白的，换你的ParallaxActivityBase 却一点事情都没有！！

**Comment by anzewei** [comment]
引入library工程到你的目录试试

**Comment by punszeto** [comment]
我现在的做法的是抽象的基类继承你的ParallaxActivityBase就正常，迟点我在试一下以引入你的工程。就在抽象基类里面直接使用你的help就总有问题。我就很郁闷了。

**Comment by anzewei** [comment]
用0.5的版本应该就好了
