### ISSUE TITLE
启动activity后不操作直接调用scrollToFinishActivity()出现白屏

### ISSUE THREAD

**Issue by 528787067** [anzewei/ParallaxBackLayout#6]
感谢分享这么好的东西，不过使用中发现了一些小问题以及提出自己的一点小建议：
bug：startActivity 后如果不对activity进行触摸操作，单击返回键在 onBackPressed() 中调用 scrollToFinishActivity()结束activity会出现白屏的问题。
建议：
1、添加类似今日头条那样可以在屏幕任意位置滑动返回的选项
2、添加activity在滑动过程的回调，这样可以实时知道当前滑动的位置以及可以做相应的处理
3、可以自定义scrollToFinishActivity()的动画时间
4、类似今日头条那样在上一级activity可以自定义添加半透明遮罩
5、可以自定义activity的边缘阴影
6、目前setLayoutType只有三种选项，希望可以增加一个自定义的选项，根据自己的需求自定义切换效果

**Comment by anzewei** [comment]
使用最新版本1.1.2
此版本以基本满足这些需求

第4条可以通过setBackgroundView在GoBackView的基础上绘制一层drawable

**Comment by 528787067** [comment]
非常感谢大神的贡献以及对我建议的采纳，不过就目前来说貌似还有点小问题，现在默认的滑动阈值是0.999f，靠手动滑动基本是达不到这个值的，因此当手指释放的时候基本是不会触发返回操作的，修改这个阈值后当滑动到阈值时马上就会触发finish()，而不管手指释放已经释放。这个问题虽然可以自己在回调中通过判断手指抬起事件来调用scrollToFinishActivity()来解决，但我觉得这个操作可以放在库中实现而不是在使用的库时候在回调中判断来实现，而且我觉得还可以进一步封装快速滑动来触发滑动返回事件，就像微信那样。还有目前来说好像还没有实现在activity任意位置滑动返回，只能在边缘滑动返回，希望大神能在库中加入这个选项，可以自定义是否在边缘触发滑动返回还是activity任意位置触发返回。这个库是我目前找到的滑动返回中最好用的一个库了，希望大神能再辛苦一下，让这个库更加强大和好用。

**Comment by anzewei** [comment]
感谢你的测试，阈值确实是我的疏忽（用错了变量），全屏滑动是因为demo中忘记加了listener，现在已经修正来了

**Comment by 528787067** [comment]
非常感谢大神的贡献
